### ISSUE TITLE
Did I understand install correctly?

### ISSUE THREAD

**Issue by cmbail** [cjbdev/TPFanControl#10]
Sorry for the noob questions. I really appreciate that you forked this and there's a chance I may be able to battle the fans on my X1E!

Your notes say: "install the original version of TPFanControl found here, and run the dual-fan version instead of the original version"

So I did:
1) Install legacy tpfancontrol from your link
2) Download repo and unzip
3) Copy all files from TPFanControl-master\fancontrol to C:\Program Files\TPFanControl

I don't see any option to run a dual-fan version. Am I supposed to compile the repo somehow?

**Comment by byrnes** [comment]
You don't have to copy any files, you just have to run the pre-built version from this repo that's located at fancontrol/Debug/fancontrol.exe. Installing the original version installs TVicPort, but if you install that manually you won't have to install the original version at all.

**Comment by cmbail** [comment]
Doh!...didn't expect to find the executable in the Debug directory, should have searched all subfolders. It runs without errors.
