### ISSUE TITLE
How to use this software

### ISSUE THREAD

**Issue by bakulaibuji** [cjbdev/TPFanControl#15]
I cannot see any .exe files in this repository. Can you help me？

**Comment by truongtrevor** [comment]
I can share exe if needed. Send me an email

**Comment by bakulaibuji** [comment]
@truongtrevor Thank you so much! My email is me_wangyx@gmail.com. I'd like to express my gratitude to you again!

**Comment by bakulaibuji** [comment]
@truongtrevor  Thank you so much! My email is me.wangyx@gmail.com. I'd like to express my gratitude to you again!

**Comment by bakulaibuji** [comment]
@truongtrevor Hey bro, i really need this exe file. Can you share it with me ?

**Comment by byrnes** [comment]
As the readme states, there is an exe provided at fancontrol/Debug/fancontrol.exe. Make sure that you install [tvicport](https://www.entechtaiwan.com/dev/port/index.shtm) as well.
