### ISSUE TITLE
Can x1 extreme with windows 10 use this?

### ISSUE THREAD

**Issue by sheep94lion** [cjbdev/TPFanControl#2]
When I run the exe file under Debug folder, it prompts "can not find tvicport.dll", I also try to build the project with vs 2018 community, but also failed.

**Comment by MarcSN311** [comment]
You have to install the driver: https://www.entechtaiwan.com/dev/port/index.shtm

**Comment by sheep94lion** [comment]
> You have to install the driver: https://www.entechtaiwan.com/dev/port/index.shtm

Thank you for your reply. I solved it by installing the original one fan version first, copying your exe file to the original one's directory and running it there. Maybe when I installed the original one, the driver was installed either?
I think it's working because when I run the original one-fan version, only one of my dual fans was runing. When I run yours, they both worked.
Thinkpad x1 extreme seems to have fan noise issue. This project is really helpful. Thanks~

**Comment by byrnes** [comment]
> > You have to install the driver: https://www.entechtaiwan.com/dev/port/index.shtm
> 
> Thank you for your reply. I solved it by installing the original one fan version first, copying your exe file to the original one's directory and running it there. Maybe when I installed the original one, the driver was installed either?
> I think it's working because when I run the original one-fan version, only one of my dual fans was runing. When I run yours, they both worked.
> Thinkpad x1 extreme seems to have fan noise issue. This project is really helpful. Thanks~

Yes, installing the original version of TPFC also installs tvicport. Make sure that you don't have both versions running at the same time, though.
