### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by archon810** [cjbdev/TPFanControl#3]
Hi,

First of all, thank you for reviving the project. I'm using it on the X1E which is a literal monster without this program.

I am having issues with encoding and was wondering if you know why things look like this:

![image](https://user-images.githubusercontent.com/469543/51357326-40121980-1a73-11e9-8de1-05fada819a93.png)

Perhaps a new build is needed to fix it?

**Comment by eternalphane** [comment]
Changing the encoding of `fancontrol.cpp`, `fanstuff.cpp` and `misc.cpp` from Windows1252 to UTF-8 will fix this issue.

**Comment by cmbail** [comment]
Same issue. I changed the encoding of all those files (in all directories; some appear three times) to UTF-8. Did not fix.

**Comment by eternalphane** [comment]
@cmbail weird. Mine was fixed with exactly the same procedure. Maybe you should double-check the file encoding.
![screenshot](https://user-images.githubusercontent.com/11267872/70229873-07198b00-1792-11ea-9d70-3c50464e6985.png)

**Comment by mihir-io** [comment]
@EternalPhane Any chance you could open a PR for you changes? I tried to do the same, but I think I just made it worse haha.

![Annotation 2019-12-05 221341](https://user-images.githubusercontent.com/5190697/70292666-c5e2a480-17ac-11ea-9ec5-23ed37b2af2e.png)

**Comment by eternalphane** [comment]
@cmbail @mihir-io Ah I see, maybe you forgot to add the pragma line below:
```cpp
#pragma execution_character_set("utf-8")
```

**Comment by mihir-io** [comment]
@EternalPhane Ah, I got it working a different way, by going into **Project** -> **fancontrol Properties** -> **Configuration Properties** -> **C/C++** -> **Command Line** -> **Additional Options** and adding `/source-charset:utf-8` in the text field. I'm in VS2019, for what it's worth. Thanks though!

**Comment by cmbail** [comment]
> @cmbail @mihir-io Ah I see, maybe you forgot to add the pragma line below:
> 
> ```c++
> #pragma execution_character_set("utf-8")
> ```

I added that line to all three files. No change.

![fancontrol_2020-01-06_10-17-05](https://user-images.githubusercontent.com/3613239/71827226-c9986e00-306d-11ea-81fe-6c3a102f1846.png)

Also checked encoding on all three files. Definitely UTF-8.

![2020-01-06_10-18-34](https://user-images.githubusercontent.com/3613239/71827306-f6e51c00-306d-11ea-8503-c5db7b7a57ba.png)

**Comment by byrnes** [comment]
Fixed by [748589af520b00812fb6159e1728f5983a2a84b7](https://github.com/cjbdev/TPFanControl/commit/748589af520b00812fb6159e1728f5983a2a84b7)
