### ISSUE TITLE
X1E control the rpm of fans directly instead of fan running level 0~7

### ISSUE THREAD

**Issue by qm1900** [cjbdev/TPFanControl#7]
Your fork do me a great favour on the widely found X1E fan issue

Thank you very much!

After using it for several days and tried different configurations for the levels, I have a further idea that might be good to provide a more subtle tweak for the fans

I noticed there are some levels 0~7, and by manual mode, found with 0 for 0rpm and 1 for around 2800 rpm

In my previous usage, I found sometimes the temperature will accumulate and approach the limit and finally reach a state of keeping oscillating around the critical value for transition from 0 to 1, that means the fan would start to run, shut down for a while, then start to run,.... 1 is noisy enough, frequent switch is still annoying

If you set up a smaller level value for 0 changing to 1, then the fan is very easy to start
if you set up a bigger level value, like mine 75C, then it accumulates and finally do things like that

I just wonder if it is possible to add functions like directly specifying the upper bounds of the rpm for each level 

that means people can set up like 
 level=50 800rpm 
 level=60 1200rpm
 level=70 2600rpm
 ...
to keep the fans running in a very lower speed with tolerable noise then the package temperature can be maintained in a steady status

So if we set up a smaller rpm than 1's for the lower temperature range to stop heat accumulation, do you think this is workable idea?

**Comment by byrnes** [comment]
Hi,

The EC on Thinkpads does not support setting the fan speed to any specific RPM, instead it only accepts values from 0 to 7. There is no way to get around this limitation as far as I'm aware.
